[env]
# disable font scaling
WINIT_X11_SCALE_FACTOR = "1.0"
# make prompt_toolkit applications (e.g., ptpython) use true colors
PROMPT_TOOLKIT_COLOR_DEPTH = "DEPTH_24_BIT"
TERM = "xterm-256color"

[general]
import = [
  "C:\\PATH_TO_USER\\AppData\\Roaming\\alacritty\\themes\\rose-pine.toml",
]
working_directory = "D:\\development\\repos"
live_config_reload = true

[terminal.shell]
program = "pwsh.exe"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"


[font]
size = 22

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[window]
title = "Hacker Man"
decorations = "full"
dynamic_title = false
option_as_alt = "Both"
startup_mode = "Windowed"

[window.dimensions]
columns = 160
lines = 80


[window.padding]
x = 1
y = 1


[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "PageUp", mods = "None", action = "ScrollPageUp", mode = "~Alt" },
  { key = "PageDown", mods = "None", action = "ScrollPageDown", mode = "~Alt" },
  { key = "Home", mods = "Shift", action = "ScrollToTop", mode = "~Alt" },
  { key = "End", mods = "Shift", action = "ScrollToBottom", mode = "~Alt" },
  { key = "N", mods = "Control", action = "SpawnNewInstance" },
  { key = "N", mods = "Control|Shift", "command" = { "program" = "alacritty.exe", "args" = [
    "--config-file",
    "C:\\PATH_TO_USER\\AppData\\Roaming\\alacritty\\alacritty.toml",
  ] } },
  { key = "Space", mods = "Control", chars = "\u0000" },
]
